In [75]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from scipy.stats import sem

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

# File to Load (Remember to Change These)
mouse_drug_data_to_load = "data/mouse_drug_data.csv"
clinical_trial_data_to_load = "data/clinicaltrial_data.csv"

# Read the Mouse and Drug Data and the Clinical Trial Data
mouse_drug = pd.read_csv(mouse_drug_data_to_load)
clinical_trial = pd.read_csv(clinical_trial_data_to_load)

# Combine the data into a single dataset
merge_table = pd.merge(mouse_drug, clinical_trial, on="Mouse ID")

# Display the data table for preview
merge_table.head()

  Mouse ID      Drug  Timepoint  Tumor Volume (mm3)  Metastatic Sites
0     f234  Stelasyn          0           45.000000                 0
1     f234  Stelasyn          5           47.313491                 0
2     f234  Stelasyn         10           47.904324                 0
3     f234  Stelasyn         15           48.735197                 1
4     f234  Stelasyn         20           51.112713                 2

## Tumor Response to Treatment

In [76]:
# Store the Mean Tumor Volume Data Grouped by Drug and Timepoint
drug_timepoint = merge_table.groupby(["Drug", "Timepoint"])
mean_tumor_value = drug_timepoint.mean()["Tumor Volume (mm3)"]

# Convert to DataFrame
tumor_mean = pd.DataFrame({"Tumor Volume (mm3)" : mean_tumor_value})

# Preview DataFrame
tumor_mean.head()

                     Tumor Volume (mm3)
Drug      Timepoint
Capomulin 0                   45.000000
          5                   44.266086
          10                  43.084291
          15                  42.064317
          20                  40.716325

In [77]:
# Store the Standard Error of Tumor Volumes Grouped by Drug and Timepoint
standard_error = drug_timepoint.sem()["Tumor Volume (mm3)"]

# Convert to DataFrame
tumor_sem = pd.DataFrame({"Standard Error" : standard_error})

# Preview DataFrame
tumor_sem.head()

                     Standard Error
Drug      Timepoint
Capomulin 0                0.000000
          5                0.448593
          10               0.702684
          15               0.838617
          20               0.909731

In [78]:
# Minor Data Munging to Re-Format the Data Frames
tumor_mean2 = tumor_mean.reset_index().pivot(index = 'Timepoint', columns = 'Drug', values = 'Tumor Volume (mm3)')
tumor_sem2 = tumor_sem.reset_index().pivot(index = 'Timepoint', columns = 'Drug', values = 'Standard Error')

# Preview that Reformatting worked
tumor_mean2.head()

Drug,Capomulin,Ceftamin,Infubinol,Ketapril,Naftisol,Placebo,Propriva,Ramicane,Stelasyn,Zoniferol
Timepoint,,,,,,,,,,
0,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000,45.000000
5,44.266086,46.503051,47.062001,47.389175,46.796098,47.125589,47.248967,43.944859,47.527452,46.851818
10,43.084291,48.285125,49.403909,49.582269,48.694210,49.423329,49.101541,42.531957,49.463844,48.689881
15,42.064317,50.094055,51.296397,52.399974,50.933018,51.359742,51.067318,41.495061,51.529409,50.779059
20,40.716325,52.157049,53.197691,54.920935,53.644087,54.364417,53.346737,40.238325,54.067395,53.170334

In [79]:
# Generate the Plot (with Error Bars)
x_axis = tumor_mean2["Timepoint"]
tumor_mean2.plot(kind="scatter", x_axis ="Timepoint", yaxis = "Drug")

plt.Titles
plt.Axes Labels,
Legend Labels
Xaxis limits
Y Axis Limits,


# Save the Figure

KeyError: 'Timepoint'

In [ ]:
# Show the Figure
plt.show()

![Tumor Response to Treatment](../Images/treatment.png)

## Metastatic Response to Treatment

In [80]:
# Store the Mean Met. Site Data Grouped by Drug and Timepoint 
mean_met_site = drug_timepoint.mean()["Metastatic Sites"]

# Convert to DataFrame
mean_met_site_pd = pd.DataFrame({"Metastatic Sites" : mean_met_site})

# Preview DataFrame
mean_met_site_pd.head()

                     Metastatic Sites
Drug      Timepoint
Capomulin 0                  0.000000
          5                  0.160000
          10                 0.320000
          15                 0.375000
          20                 0.652174

In [81]:
# Store the Mean Met. Site Data Grouped by Drug and Timepoint 
sem_met_site = drug_timepoint.sem()["Metastatic Sites"]

# Convert to DataFrame
sem_met_site_pd = pd.DataFrame({"Standard Error" : sem_met_site})

# Preview DataFrame
sem_met_site_pd.head()

                     Standard Error
Drug      Timepoint
Capomulin 0                0.000000
          5                0.074833
          10               0.125433
          15               0.132048
          20               0.161621

In [91]:
# Minor Data Munging to Re-Format the Data Frames
mean_met_site2 = mean_met_site_pd.reset_index().pivot(index = 'Timepoint', columns = 'Drug', values = 'Metastatic Sites')
sem_met_site2 = sem_met_site_pd.reset_index().pivot(index = 'Timepoint', columns = 'Drug', values = 'Standard Error')

# Preview that Reformatting worked
mean_met_site2.head()

Drug,Capomulin,Ceftamin,Infubinol,Ketapril,Naftisol,Placebo,Propriva,Ramicane,Stelasyn,Zoniferol
Timepoint,,,,,,,,,,
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
5,0.160000,0.380952,0.280000,0.304348,0.260870,0.375000,0.320000,0.120000,0.240000,0.166667
10,0.320000,0.600000,0.666667,0.590909,0.523810,0.833333,0.565217,0.250000,0.478261,0.500000
15,0.375000,0.789474,0.904762,0.842105,0.857143,1.250000,0.764706,0.333333,0.782609,0.809524
20,0.652174,1.111111,1.050000,1.210526,1.150000,1.526316,1.000000,0.347826,0.952381,1.294118

In [ ]:
# Generate the Plot (with Error Bars)

# Save the Figure

# Show the Figure

![Metastatic Spread During Treatment](../Images/spread.png)

## Survival Rates

In [86]:
# Store the Count of Mice Grouped by Drug and Timepoint (W can pass any metric)
mice_count = drug_timepoint.nunique()["Mouse ID"]

# Convert to DataFrame
mice_count_pd = pd.DataFrame({"Mouse Count" : mice_count})

# Preview DataFrame
mice_count_pd.head()

                     Mouse Count
Drug      Timepoint
Capomulin 0                   25
          5                   25
          10                  25
          15                  24
          20                  23

In [90]:
# Minor Data Munging to Re-Format the Data Frames
mice_count_pd2 = mice_count_pd.reset_index().pivot(index = 'Timepoint', columns = 'Drug', values = 'Mouse Count')

# Preview that Reformatting worked
mice_count_pd2.head()

Drug,Capomulin,Ceftamin,Infubinol,Ketapril,Naftisol,Placebo,Propriva,Ramicane,Stelasyn,Zoniferol
Timepoint,,,,,,,,,,
0,25,25,25,25,25,25,25,25,25,25
5,25,21,25,23,23,24,24,25,24,24
10,25,20,21,22,21,24,22,24,22,22
15,24,19,21,19,21,20,16,24,22,21
20,23,18,20,19,20,19,16,23,20,17

In [ ]:
# Generate the Plot (Accounting for percentages)

# Save the Figure

# Show the Figure
plt.show()

![Metastatic Spread During Treatment](../Images/survival.png)

## Summary Bar Graph

In [ ]:
# Calculate the percent changes for each drug

# Display the data to confirm

Drug
Capomulin   -19.475303
Ceftamin     42.516492
Infubinol    46.123472
Ketapril     57.028795
Naftisol     53.923347
Placebo      51.297960
Propriva     47.241175
Ramicane    -22.320900
Stelasyn     52.085134
Zoniferol    46.579751
dtype: float64

In [ ]:
# Store all Relevant Percent Changes into a Tuple


# Splice the data between passing and failing drugs


# Orient widths. Add labels, tick marks, etc. 


# Use functions to label the percentages of changes


# Call functions to implement the function calls


# Save the Figure


# Show the Figure
fig.show()

![Metastatic Spread During Treatment](../Images/change.png)